package life.majiang.community.model;

public class Images {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGES.ID
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGES.NAME
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGES.DATA
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGES.ID
     *
     * @return the value of IMAGES.ID
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGES.ID
     *
     * @param id the value for IMAGES.ID
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGES.NAME
     *
     * @return the value of IMAGES.NAME
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGES.NAME
     *
     * @param name the value for IMAGES.NAME
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGES.DATA
     *
     * @return the value of IMAGES.DATA
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGES.DATA
     *
     * @param data the value for IMAGES.DATA
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}