package life.majiang.community.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTABLE.ID
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTABLE.ACCOUNT_ID
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTABLE.NAME
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTABLE.TOKEN
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTABLE.GMT_CREATE
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTABLE.GMT_MODIFIED
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTABLE.PASSWORD
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTABLE.BIO
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERTABLE.AVATAR_URL
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTABLE.ID
     *
     * @return the value of USERTABLE.ID
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTABLE.ID
     *
     * @param id the value for USERTABLE.ID
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTABLE.ACCOUNT_ID
     *
     * @return the value of USERTABLE.ACCOUNT_ID
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTABLE.ACCOUNT_ID
     *
     * @param accountId the value for USERTABLE.ACCOUNT_ID
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTABLE.NAME
     *
     * @return the value of USERTABLE.NAME
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTABLE.NAME
     *
     * @param name the value for USERTABLE.NAME
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTABLE.TOKEN
     *
     * @return the value of USERTABLE.TOKEN
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTABLE.TOKEN
     *
     * @param token the value for USERTABLE.TOKEN
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTABLE.GMT_CREATE
     *
     * @return the value of USERTABLE.GMT_CREATE
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTABLE.GMT_CREATE
     *
     * @param gmtCreate the value for USERTABLE.GMT_CREATE
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTABLE.GMT_MODIFIED
     *
     * @return the value of USERTABLE.GMT_MODIFIED
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTABLE.GMT_MODIFIED
     *
     * @param gmtModified the value for USERTABLE.GMT_MODIFIED
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTABLE.PASSWORD
     *
     * @return the value of USERTABLE.PASSWORD
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTABLE.PASSWORD
     *
     * @param password the value for USERTABLE.PASSWORD
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTABLE.BIO
     *
     * @return the value of USERTABLE.BIO
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTABLE.BIO
     *
     * @param bio the value for USERTABLE.BIO
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERTABLE.AVATAR_URL
     *
     * @return the value of USERTABLE.AVATAR_URL
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERTABLE.AVATAR_URL
     *
     * @param avatarUrl the value for USERTABLE.AVATAR_URL
     *
     * @mbg.generated Wed Jun 05 15:26:54 CST 2024
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}