package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Images;
import life.majiang.community.model.ImagesExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    long countByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int deleteByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int insert(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int insertSelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    List<Images> selectByExampleWithBLOBsWithRowbounds(ImagesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    List<Images> selectByExampleWithBLOBs(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    List<Images> selectByExampleWithRowbounds(ImagesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    List<Images> selectByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    Images selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int updateByExampleSelective(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int updateByExample(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int updateByPrimaryKeySelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGES
     *
     * @mbg.generated Wed Jul 10 10:13:52 CST 2024
     */
    int updateByPrimaryKey(Images record);
}